### ISSUE TITLE
Using outside gumby framework

### ISSUE THREAD

**Issue by Pandahisham** [GumbyFramework/InView#3]
I am using another framework with jquery , how  can i use it ?

**Comment by motionharvest** [comment]
Well, lets see. It needs heavy modification in order to do that. However, you might be interested in a related project that I've developed - inspired by my work on the InView plugin for triggering functions when elements are between 2 places on the the screen. Its not 100% complete, but it has the basics that InView had but with a different implementation. https://github.com/cmndo/RenderFarm/tree/v3

**Comment by Pandahisham** [comment]
I found a suitable plugin , thanks for your prompt reply , (and sorry for my delayed response)
